[package]
name = "okta_example_management_app"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"
publish = false

[dependencies]
lazy_static = "1.4"
ockam = { path = "../../../../ockam" }
ockam_vault = {  path = "../../../../ockam_vault" }
ockam_vault_sync_core = {  path = "../../../../ockam_vault_sync_core" }
okta-plugin = { path = "../" }
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
