[package]
name = "node_examples"
version = "0.0.0"
authors = ["Ockam Developers"]
edition = "2018"
publish = false
autobins = false

[dependencies]
ockam = { path = "../../../ockam" }
ockam_node = { path = "../../../ockam_node" }

# TODO: this dependency here is required because rustc doesn't yet
# support re-exporting attributes from crates.  Tracking issue:
# https://github.com/rust-lang/rust/issues/27812
serde = { version = "1.0", features = ["derive"] }
